### ISSUE TITLE
Explicitly prohibit ICE mismatch processing

### ISSUE THREAD

**Issue by martinthomson** [rtcweb-wg/jsep#121]
When JSEP recommends that `c=` lines are ignored (absent some syntax validation), it violates a rule in RFC 5245 regarding mismatch processing.  5245 requires that the values for port and IP address in `c=` and `m=` correspond to a candidate that appears in the media section.

Consensus in Dallas was to prohibit checking of the value in `c=` against `m=` and `a=candidate:`, which requires an explicit mention in the draft, since this is different to what 5245 says.

**Comment by juberti** [comment]
The sole point of mismatch processing is to allow applications to see if some SBC messed with their addresses:

  If the agent is not proceeding with ICE because there were
       a=candidate attributes, but none that matched the default
       destination of the media stream, the agent MUST include an a=ice-
       mismatch attribute in its answer.

Not proceeding with ICE isn't an option here, and this is somewhat problematic with trickle ice (at least the initial 0.0.0.0 candidate), so I think ignoring makes sense.
