### ISSUE TITLE
Section 5.1.3:  Should UDP/TLS/RTP/SAVPF be used in all cases where UDP is used?

### ISSUE THREAD

**Issue by hardie** [rtcweb-wg/jsep#394]
Originally raised by Magnus:

 For media m= sections, JSEP endpoints MUST support both the "UDP/TLS/
   RTP/SAVPF" and "TCP/DTLS/RTP/SAVPF" profiles and MUST indicate one of
   these two profiles for each media m= line they produce in an offer.

Do I understand this correct, we are requiring support for the "TCP/DTLS/RTP/SAVPF" proto so that in cases an endpoint supports the optional to support ICE TCP, they can indicate it, and any WebRTC endpoint will accept it, even if that is just one option? I do know that different profiles are a negotiation issue. But, wouldn't it be more reasonable in this case to use UDP/TLS/RTP/SAVPF in all cases where one offer any candidates that also use UDP? And only use TCP/DTLS/RTP/SAVPF in cases only TCP candidates are signalled, thus not forcing TCP/DTLS/RTP/SAVPF onto clients that doesn't support it?

**Comment by ekr** [comment]
I think we've already agreed that WebRTC implementations are going to mostly ignore what's in these fields because all the parameters they indicate (TCP vs UDP, SRTP, Feedback) are resolved via extensions. Whatever we put here is just to satisfy the smallish number of old endpoints which (a) care what's in this field and (b) implement ICE, DTLS, etc. So with that said, I'm happy to require UDP and not TCP, but this seems largely irrelevant to implementations as a practical matter. PR wanted.

**Comment by ekr** [comment]
I think we closed this in the MMUSIC meeting, but I need to go back and look at the minutes.

**Comment by ekr** [comment]
Not so simple. Mail sent to list.

**Comment by ekr** [comment]
Editor consensus was to just use UDP all the time. Closing this.
