### ISSUE TITLE
Section 5.8: Clarification of language setting the MID attribute for m= section

### ISSUE THREAD

**Issue by hardie** [rtcweb-wg/jsep#402]
Originally raised by Magnus:

Section 5.8:

         +  Find the RtpTransceiver that corresponds to the m= section
            with the same MID in the created offer.

         +  Set the value of the RtpTransceiver's mid attribute to the
            MID of the m= section.

I find this text strange. If you already know the MID, why is it being set in the second sub-bullet?

**Comment by fluffy** [comment]
seems like we just need to check this  - prob. editorial

**Comment by juberti** [comment]
I think this is just an artifact of how the createOffer sequence works:
1) addTrack - creates transceiver with no MID
2) createOffer - creates MIDs but doesn't assign them
3) setLocal - assigns MIDs to transceivers
@pthatcherg, is this correct?

Agree that it's a bit confusing at first glance and perhaps we could explain it better.

**Comment by juberti** [comment]
@gloinul for his comments

**Comment by taylor-b** [comment]
Speaking for pthatcherg, yes, that's how we designed it. You can think of the MID in the offer as a "proposed" MID, until setLocalDescription is called.

Part of the reason for this is to simplify some corner cases. For example: createOffer is called and proposes a MID "foo", but before the offer is applied, setRemoteDescription is called, and one of the remote m= sections also happens to use MID "foo". Now when generating a subsequent offer, a different MID would need to be proposed for the new m= section, because you can't have 2 m= sections with the same MID.

**Comment by juberti** [comment]
ping @gloinul

**Comment by pthatcherg** [comment]
Justin's understanding and Taylor explanation are correct.  Before setLocal is called, transceivers aren't "associated" with any m=section, and thus have no MID.

**Comment by pthatcherg** [comment]
I think Taylor's clarification PR is good.

**Comment by gloinul** [comment]
Yes, the PR appears to resolve my issue. Thanks!

**Comment by juberti** [comment]
Resolved by #471
