### ISSUE TITLE
Apply local description - return to previous state on failure?

### ISSUE THREAD

**Issue by alvestrand** [rtcweb-wg/jsep#429]
Section 5.8 Applying a local description - on errrors, "processing
MUST stop and an error MUST be returned" - should it also say that the
state of the PC needs to be returned to the pre-apply-LD state?

**Comment by juberti** [comment]
I'm not sure this is always possible. A failure here may leave the PC fatally broken (e.g. failure after discarding of RTCP ICE component)

**Comment by taylor-b** [comment]
You could argue this is a deficiency with the implementation though. It could wait to discard the RTCP ICE component until after everything else succeeded. Or, more generally, wait to release existing resources until after new resources are successfully acquired.

**Comment by alvestrand** [comment]
I'd be happy with text that says that it either must return to the pre-LD state or go to the closed state - but the way it is written now, there are no guarantees about the internal consistency of the state of the PC after an error is returned from SetLocalDescription.

**Comment by juberti** [comment]
I guess we could say in the spec that the operation is rolled back, and implementations could decide whether or not it's worth the trouble to actually implement this fully. 

Moving to closed would be somewhat unusual since the only thing that results in this state today is a close() call.

Generally, I think this is an academic question since an error will almost certainly be fatal to the session; the app isn't going to retry API calls.

**Comment by alvestrand** [comment]
If an error is fatal to the session, it needs to go to closed() (or some error state).

What I want to say is that the result of rollback is either the previous state or a failure. I don't want any lazy implementor (me?) to write code that rolls back "everything except this bit over here, because it was too hard" and leaves things in a confused state.
