### ISSUE TITLE
Do subsequent offers contain a=bundle-only for existing m= lines?

### ISSUE THREAD

**Issue by juberti** [rtcweb-wg/jsep#509]

**Comment by taylor-b** [comment]
If my interpretation is correct, the answer is no:

> Once the offerer BUNDLE address has been selected, the offerer does not need to include the 'bundle-only' attribute in subsequent offers.  By associating the offerer BUNDLE address with an "m=" line of a subsequent offer, the offerer will ensure that the answerer will either keep the "m=" line within the BUNDLE group, or the answerer will have to reject the "m=" line.

In other words: In a subsequent offer, you don't need to use "bundle-only" because you can force things to remain bundled by just not offering unique addresses for different "m=" sections. Or in the case of ICE, only putting the "ice-ufrag"/"ice-pwd" in one "m=" section.

**Comment by juberti** [comment]
OK. We might need to reiterate this in JSEP.

**Comment by juberti** [comment]
Waiting for @taylor-b 's email to the list to resolve.

**Comment by fluffy** [comment]
talked to chairs and advice from chairs on this and similar things that depend on mmusic outcomes. We put in JSEP now what our best guess is of how mmusic will end up and publish JSEP. At the same time we log a bug to check if we need to make any changes to line up with what mmusic decides. We can take changes to line up with mmusic as Last Call comments later on.

**Comment by fluffy** [comment]
I can't see why subsequent offer should not have the bundle-only. Agree that it is bundles problem but it seems bundle should change to have them.

**Comment by ekr** [comment]
OK I have finally reloaded my state here.

The basic way that BUNDLE works is that you can say:

  a=group:BUNDLE A B
  m=video 9
  a=mid:A
  m=video 9
  a=mid:B

And the answerer can take any of A, B or both. However, because we don't
want to gather for both A and B, we might want to say "you can only take
B if you take A". You do this bu:

- A 0 port which which says "you shouldn't use this m= line"
- An a=bundle-only line which says "actually, you can use this m= line if
  you bundle it with someone else"


I.e.,

  a=group:BUNDLE A B
  m=video 9
  a=mid:A
  m=video 0
  a=mid:B
  a=bundle-only

This means that the answerer can now take A or (A, B) but not B alone.


I take Christer's point to be that once we have done that, if the answerer
took (A, B), if a subsequent offer contains:

  a=group:BUNDLE A B
  m=video 10000
  a=mid:A
  m=video 10000
  a=mid:B

Then the answerer can take any subset of (A, B) again, and this is free
because the offerer doesn't need to re-gather, as the over-gathering issue
only happened on the first offer. Note, however, that if you are co-locating
this with an ICE restart, then you're back in the situation where this isn't
free.


There are actually two questions here:

1. What BUNDLE says you can/can't/should do
2. What JSEP recommends.

I think BUNDLE should just describe the semantics, and both semantics are
valid here. You can perfectly well use a zero port and a=bundle-only on
a re-offer and that means one thing and a non-zero port means another.
The JSEP question is what a *policy* of max-bundle means. Given that you
can't take things out of the bundle group when bundle-only is used on the
initial offer and that the other side can re-offer, I think we should make
things simple and suggest that JSEP implementations generate bundle-only
and zero ports all the time.

**Comment by juberti** [comment]
Resolved by #588.
