### ISSUE TITLE
Do we need ref for RFC5583 (a=depend)

### ISSUE THREAD

**Issue by fluffy** [rtcweb-wg/jsep#566]

**Comment by juberti** [comment]
For context, this is for MRST/MRMT SVC scenarios. https://tools.ietf.org/html/rfc5583.

Generally, I think we want to promote SRST as the preferred way to do SVC, but we might still need to say something about a=depend. @aboba, wdyt?

**Comment by aboba** [comment]
@juberti  At this point, the only MRST implementation of H.264/SVC I am aware of is Microsoft's.  All other implementations are SRST.  We chose not to expose H.264UC (our variant of H.264/SVC) in our native WebRTC 1.0 implementation.  It didn't seem worthwhile since we didn't expect any other browser to implement it.   So we only expose H.264UC in the ORTC API which causes it to show up in WebRTC 1.0 API provided via adapter.js running over ORTC.  BTW, adapter.js just exposes H.264UC like H.264/AVC with no RFC 5583 a=depend lines.  So far, noone has complained about our omission of H.264UC from the native WebRTC 1.0 implementation.  Given that AV1 will be SRST I do not see much future need for MRST support in SVC.

I am not sure we need any specific advice relating to RFC 5583 in JSEP, assuming the implementations ignore a= lines they don't understand and properly handle codecs they don't support.

**Comment by juberti** [comment]
OK. If @aboba has the only implementation, and doesn't see a need here, I suggest we take no action.
