### ISSUE TITLE
Are there any uses of "pranswer" that aren't required to be supported?

### ISSUE THREAD

**Issue by taylor-b** [rtcweb-wg/jsep#600]
Changing the codecs, header extensions, etc. from the provisional answer to the real answer is, in theory, pretty simple to implement. Other things, however - related to connection-oriented protocols - are more complex.

- Changing the ICE ufrag/password. Should this result in a non-standard "half" ICE restart (continuing to use the previously selected candidate pair), or should it result in ICE state being completely restored to the point before the "pranswer" was applied? Also, if this is supported, it means ICE candidates can't be deallocated until a final answer is applied. This may be already implied by "should not result in the freeing of allocated resources."
- Changing the DTLS fingerprint and/or "a=setup". Should this result in a new DTLS association? This involves some non-trivial interactions with ICE; see [dtls-sdp](https://tools.ietf.org/html/draft-ietf-mmusic-dtls-sdp-16#section-6). Also, if two "pranswers" that establish new DTLS associations are in-flight (due to slow signaling), it becomes hard to tell which association a given "Client Hello" is for, unless I'm not considering something. A robust implementation would need to have multiple DTLS associations going in parallel, one per remote ICE ufrag, and throw them away as answers arrive and it can be determined which one is the oldest.
- Changing the SCTP port. Does this result in a new SCTP association?

Are these things intended to be supported? If so, it might be worthwhile clarifying a bit how they should work.

**Comment by fluffy** [comment]
We don't really care about what SIP would call parallel forking so the answer is "probably not needed". Here is a case to consider that is very related but does not involve pranswer.

A makes offer and gets answer from B and sets up connection - let me call that OA1. Now A makes reoffer. ICE stuff stays the same because it is connected to same ICE GW but at the far end the certificate is and DTLS connection are going to change because it ended up at a different end point. Before an answer is sent to the 2n'd offer, can the 2n'd DTLS connection be  set up ? Does that tear down the first one ? If you roll back, does a new DTLS connection have to be formed for the OA1. 

If you go with only one TLS connection at time , it means you get a media blip after the answer for OA2 is installed while the DTLS comes up. I sort of assume current implementations don't really deal with this at all but I have not tried any of it.

**Comment by taylor-b** [comment]
> ICE stuff stays the same because it is connected to same ICE GW but at the far end the certificate is and DTLS connection are going to change because it ended up at a different end point. 

This isn't allowed unless the offerer initiates an ICE restart. This is touched on in the thread for #448.

> Before an answer is sent to the 2n'd offer, can the 2n'd DTLS connection be set up ?

Yes.

> Does that tear down the first one ?

Not until the answer is applied.

> If you roll back, does a new DTLS connection have to be formed for the OA1

No, because the old association should still be there.

> I sort of assume current implementations don't really deal with this

I know Chrome doesn't. :)
But I consider that a bug.

**Comment by ekr** [comment]
@taylor-b: can you write something up. @juberti will provide a summary

**Comment by juberti** [comment]
The intent here was that changing of the remote-ufrag in a successive answer essentially incinerates all the current remote ICE state - all candidates, candidate pairs, selected pair, etc.

Same for the changing of the remote fingerprint; this should incinerate the remote DTLS state, and any existing association.

If the SCTP port hasn't changed, there's no signal indicating we need to incinerate the remote SCTP state, but that somehow needs to happen since the new endpoint won't have any SCTP state.

**Comment by juberti** [comment]
For your amusement, this was discussed briefly in 2012, and I suppose never incorporated into the document: https://docs.google.com/presentation/d/1PkSnC25CX2hk42dyLAySGb_3_2Oea913eLkAmUqLHZA/edit#slide=id.gde70e74_0_77

I believe this should go into the "Applying a Remote Description" section.

**Comment by fluffy** [comment]
Wow - those guys were on the case back 2012 :-)

**Comment by taylor-b** [comment]
In addition to the rule "when you get a new answer, you incinerate previous state", what may not be so obvious is that after sending an offer, the offerer needs to be prepared to receive early media from _multiple_ different endpoints, which is only possible with the existence of "pranswer". Example:

1. Offer sent
2. STUN binding request received with remote ICE ufrag "foo"
3. STUN binding request received with remote ICE ufrag "bar"
4. DTLS Client Hello received on the "foo" candidate pair.
5. DTLS Client Hello received on the "bar" candidate pair.
6. "pranswer" arrives with ufrag "bar" (now we know which association is oldest).
7. DTLS handshake continues on "bar" candidate pair.
8. "pranswer" arrives with ufrag "foo". "bar" association incinerated.

**Comment by juberti** [comment]
Yes, that is an interesting wrinkle. Since this is such an edge case though, I would suggest that implementations should be allow to only handle one remote username at a time. IOW, in the case you mention, the STUN check for "bar" would be eaten, and DTLS would not start for "bar", until the pranswer arrives, which causes the "foo" state to be eaten, and future checks for "bar" to be processed.

Otherwise, you have the possibility of maintaining N simultaneous ICE and DTLS connections while you wait to discard all but one of them. If we were going to support that, we would probably want to go all the way and support parallel forking.

**Comment by juberti** [comment]
@taylor-b , will you be able to write something up for this? Trying to get a version of the document out next week for WGLC review.

**Comment by taylor-b** [comment]
Yeah, I'll get it written up this weekend.
