### ISSUE TITLE
RFC 5245 contradiction

### ISSUE THREAD

**Issue by juberti** [rtcweb-wg/jsep#636]
BLOCKER: The text in the third paragraph of section 5.7.1 intentionally contradicts language in RFC 5245; as such, this document needs to formally update that RFC. Note that updated RFCs are expected to be mentioned in the Abstract as well as the document metadata.

**Comment by juberti** [comment]
@ekr, @fluffy, what's your take on this?

**Comment by fluffy** [comment]
So we have two choices here 

1) Do what ICE says from a normative point of view but point out you can ignore this is you implementation does not implement the ICE mismatch stuff which is required for a fully compliant ICE implementation. 

2) Make this spec update 5245 to remove the requirement to implement any of the ICE mismatch stuff when using ICE with WebRTC. I am afraid that will turn into a nightmare of "what exact text is changed in 5245" and that might be a bunch because "mismatch" shows up a bunch in 5245. 

I guess I lean towards 1 but I can go either way.

**Comment by juberti** [comment]
Maybe the simplest path here is that we say the c= does need to match what is mentioned in 5245/trickle, since that should be the case already if you are following JSEP properly.

IOW, perhaps we just avoid accepting garbage by enforcing this. Implementations of course can skip this check if they are lazy.
