### ISSUE TITLE
JSEP says that subsequent offers need to specify the ICE protocol

### ISSUE THREAD

**Issue by juberti** [rtcweb-wg/jsep#854]
This contradicts the guidance in 5.1.2 Profile Names, which says impls MUST indicate
the UDP/TLS/RTP/SAVPF profile for each media m= line they produce in an offer.

Introduced in https://github.com/rtcweb-wg/jsep/commit/e8fd5c67e7fa09c6c0c171739449a7271de58fc7, which predates our decision to not use active ICE protocols in the m= line. 

Note that sip-sdp, S 3.3.4 still says that the active ICE protocol needs to be included.

**Comment by rshpount** [comment]
Using IP and port but not the proto for the default candidate is confusing and ambiguous. Nothing prevent end point to have two candidate, one UDP and another TCP, which both have the same address and port with only difference being the protocol. 

I think there are two possible options here:

1. Always use a place holder instead of default candidate in c= and m= line (IN IP4 0.0.0.0 and port 9)
2. Use the proto for the actual transport used

The benefit of option 1 is that c= and m= line never change. Since ICE is always used, information in c= and m= line serves little purpose and can be safely ignored. This will simplify code a little bit.

The benefit of option 2 is consistency, but complicates implementation since c= and m= line can change, including proto.

In any case, proto value in m= line stays the same throughout the transaction.

**Comment by juberti** [comment]
This was previously litigated in https://github.com/rtcweb-wg/jsep/issues/394 and https://mailarchive.ietf.org/arch/msg/mmusic/gR-dYY1GzN3fIA_XlHiX-bB6nLM and the consensus was to always use UDP.

**Comment by rshpount** [comment]
First of all, I do not think this is the final consensus. I think the final language was something like the one in https://tools.ietf.org/html/draft-ietf-mmusic-sctp-sdp-26#section-12.2:

> In order to maximize the likelihood of interoperability between the
> endpoints, all ICE enabled SCTP-over-DTLS endpoints SHOULD implement
> support for UDP/DTLS/SCTP.
> 
> When an SDP offer or answer is sent with multiple ICE candidates
> during initial connection negotiation or after ICE restart, UDP based
> candidates SHOULD be included and default candidate SHOULD be chosen
> from one of those UDP candidates.  The proto value MUST match the
> transport protocol associated with the default candidate.  If UDP
> transport is used for the default candidate, then 'UDP/DTLS/SCTP'
> proto value MUST be used.  If TCP transport is used for the default
> candidate, then 'TCP/DTLS/SCTP' proto value MUST be used.  Note that
> under normal circumstances the proto value for offers and answers
> sent during ICE nomination SHOULD be 'UDP/DTLS/SCTP'.
> 
> When a subsequent SDP offer or answer is sent after ICE nomination is
> complete, and does not initiate ICE restart, it will contain only the
> nominated ICE candidate pair.  In this case, the proto value MUST
> match the transport protocol associated with the nominated ICE
> candidate pair.  If UDP transport is used for the nominated pair,
> then 'UDP/DTLS/SCTP' proto value MUST be used.  If TCP transport is
> used for the nominated pair, then 'TCP/DTLS/SCTP' proto value MUST be
> used.  Please note that if an endpoint switches between TCP-based and
> UDP-based candidates during the nomination process the endpoint is
> not required to send an SDP offer for the sole purpose of keeping the
> proto value of the associated m- line in sync.


Second, I think discussion in this thread was about the initial offer or any offer which does ICE restart and contains multiple candidates. It was not talking about the subsequent request case when only a single candidate is present.

Finally, I think in case of JSEP, it is fine to always use the UDP based protocol, but it should be used with transport address "0.0.0.0"/"::" and port value of "9" or a real UDP candidate. If candidate address and port are used with a transport proto that does not match an actual candidate, this will be treated as either mismatch or additional candidate (https://tools.ietf.org/html/draft-ietf-mmusic-ice-sip-sdp-23#section-3.2.5). I do not think this is desirable.

**Comment by juberti** [comment]
If you feel strongly about this, I think you need to raise it on the list, as the artifacts I provided indicate there was consensus for this position.

I don't think we can use a bogus candidate without triggering ICE mismatch.

**Comment by rshpount** [comment]
The language that I quoted was what actually discussed on mmusic and went into the draft. Same thing goes for the ICE-SIP-SDP, which talks about using the actual proto in subsequent requests. I do not see anything in the messages that you quote that confirms what is written in JSEP (IP and port of the actual candidate but with the different proto being used in subsequent requests). We should take this to the list since there is definitely a mismatch between sctp-sdp, ice-sip-sdp, and jsep.

P.S. Using m= line with port 9 and c= line with address 0.0.0.0 or "::" was added to ice-sip-sdp specifically for the purpose of avoiding triggering ICE mismatch.

**Comment by juberti** [comment]
OK, seems like we should resolve this mismatch. Interesting point about ice-sip-sdp, that feels like the better option of the two you proposed.

**Comment by juberti** [comment]
cc @ekr if he has any thoughts on this

**Comment by ekr** [comment]
We discussed this in Bangkok and consensus was to never change the proto field

**Comment by rshpount** [comment]
What did you decide to put in port on m= line and address in c= line?

**Comment by ekr** [comment]
We didn't discuss but I would assume we would follow sip-sdp

**Comment by rshpount** [comment]
My proposal was to use  TCP/DTLS/blah whenever the default candidate is a
TCP candidate and *ICE nomination is complete*. If TCP candidate become
default candidate after ICE nomination is complete, both end points should
support  TCP/DTLS  based protocol. In all other cases, candidates are
either still being collected or UDP candidate should be present and used as
default.

In the initial offer, when ICE nomination is in progress, when ICE restart
is initiated, end points must still use UDP based proto, since we do not
want them to send TCP based offer if remote does not support it or change
the proto during the ICE negotiation.

Regards,
_____________
Roman Shpount

**Comment by juberti** [comment]
@rshpount, selection of the default candidate is up to the discretion of the implementation, so I don't think this additional condition is necessary. Naturally, when restarting ICE, the implementation will typically again generate UDP candidates, and so the default in that case will be a UDP candidate.
