### ISSUE TITLE
backward compability with endpoint that do not send a=msid and only a single audio/video stream

### ISSUE THREAD

**Issue by fippo** [rtcweb-wg/jsep#856]
Take this simplified SDP offer from a remote endpoint (in parts taken from [here](https://tools.ietf.org/html/draft-ietf-rtcweb-sdp-11#section-5.2.2.1):
```
v=0
o=- 20518 0 IN IP4 0.0.0.0
s=-
t=0 0
m=audio 9 UDP/TLS/RTP/SAVPF 109
c=IN IP4 203.0.113.141
a=sendrecv
a=rtpmap:109 opus/48000/2
a=ice-ufrag:074c6550
a=ice-pwd:a28a397a4c3f31747d1ee3474af08a068
a=fingerprint:sha-256 19:E2:1C:3B:4B:9F:81:E6:B8:5C:F4:A5:A8:D8:73:04:BB:05:2F:70:9F:04:A9:0E:05:E9:26:33:E8:70:88:A2
a=setup:actpass
m=video 9 UDP/TLS/RTP/SAVPF 99
c=IN IP4 203.0.113.141
a=sendrecv
a=rtpmap:99 H264/90000
a=fmtp:99 profile-level-id=4d0028;packetization-mode=1
a=ice-ufrag:074c6550
a=ice-pwd:a28a397a4c3f31747d1ee3474af08a068
a=fingerprint:sha-256 19:E2:1C:3B:4B:9F:81:E6:B8:5C:F4:A5:A8:D8:73:04:BB:05:2F:70:9F:04:A9:0E:05:E9:26:33:E8:70:88:A2
a=setup:actpass
```
A single audio and video stream. No a=mid (there is quite some text taking care of that) but no a=msid line either. https://jsfiddle.net/5jd8Lz97/1/ shows a live example.

Both Chrome (without unified-plan) and Firefox will fire the ontrack event (or legacy onaddstream) with a single mediastream containing an audio and video track. This has been like that since... 2012-ish?

Unified plan support in Chrome changes this behaviour: https://jsfiddle.net/5jd8Lz97/
ontrack is fired with an empty set of media streams. onaddstream is not fired.

This is quite a change in behaviour. And unexpected, I didn't expect any issues for this trivial case of a single audio/video track.

As @henbos [pointed out](https://bugs.chromium.org/p/chromium/issues/detail?id=901711) webrtc-pc assumes/requires a=msid to be present[here](https://w3c.github.io/webrtc-pc/#processing-remote-mediastreamtracks) and [here](https://w3c.github.io/webrtc-pc/#set-the-rtcsessiondescription). In particular this says
```
If direction is "sendrecv" or "recvonly", let msids be a list of the MSIDs that the media 
description indicates transceiver.[[Receiver]].[[ReceiverTrack]] is to be associated with.
Otherwise, let msids be an empty list.
```
which means firing with no streams is technically correct.

JSEP seems to assume it is present as well, but has this text about a=msid in [5.8.2](https://tools.ietf.org/html/draft-ietf-rtcweb-jsep-24#section-5.8.2)
```
 If present, "a=msid" attributes MUST be parsed as specified in
      [I-D.ietf-mmusic-msid], Section 3.2, and their values stored.
```
Note the "If present". What if it is not present?

The closest I could find in terms of guidance was this from the [msid draft](https://tools.ietf.org/html/draft-ietf-mmusic-msid-16)
```
   It follows from the above that MediaStreamTracks in the "default"
   MediaStream cannot be closed by removing the msid attribute;
```
and its section about handling [non-signalled tracks](https://tools.ietf.org/html/draft-ietf-mmusic-msid-16#section-3.1)

a=msid is supposed to be present in initial offer so we are talking about dealing with non-webrtc entities send an offer. Given that there is plenty of support for entities that do not support a=mid (an RFC published in 2010) in JSEP do we need backward compability for the case of a single audio/video track each but no msid?

Interop between browsers is probably not affected, due to Chrome still interpreting and sending a=ssrc:123 msid:...

**Comment by fippo** [comment]
note that a proper webrtc client will include "no streams" as `a=msid:-`(maybe with a track) which allows differentiating between "no streams because I do not use any" and "msid???"

Thanks @jan-ivar for another [great fiddle](https://jsfiddle.net/jib1/jfz08oyd/)

**Comment by alvestrand** [comment]
aside: the interesting case you have trouble distinguishing between is "no msid because I haven't started sending a track yet" and "no msid because I don't support msid".
It's one case where we still have trouble if RTP packets arrive ahead of signalling.

But - yes, I think we are better off sticking with the 2012 behavior, default stream and all.

**Comment by fippo** [comment]
there used to be a a=msid-semantic line that would allow determining whether a party wants its offer to be treated assuming msid support. Browsers still send it :-)

**Comment by henbos** [comment]
How are non-signaled tracks supposed to be handled anyway? There's JSEP language about creating a track for it, but what about webrtc-pc? (If a track exists in the forest, and nobody is around to surface it to JavaScript, does it still exist?)

"Run the following steps for each media description in _description_" means no ontrack will fire until we _do_ have something signaled. If the track (and/or stream) only exists in some inaccessible way they're almost conceptual until the signaling does arrive. And when it does arrive, we know whether or not MediaStreams were signaled. So we should know what to do, same things as if we didn't receive early RTP packets? Does the distinction matter?

I love that we can tell the difference between "no streams because I do not use any" and "no msid signaled" whether or not "a=msid:-" was present. I had not thought about that! Unless I'm confused about something, I suggest:

- If `a=msid:-` is present, do what Chrome does: don't create any stream.
- If the `a=msid` line is completely missing, do what Firefox (or Chrome Plan B) does: create a MediaStream with a random id.

Does that work for people?

**Comment by henbos** [comment]
By the way I thought this was a webrtc-pc issue when I replied above, so I was thinking about what to do in JavaScript rather than talking about any JSEP change.

**Comment by fippo** [comment]
I suppose we need some JSEP language to handle the lack of any a=msid but i agree with what you propose above. We do have have a=msid:- and we need to handle that in webrtc-pc too. Will file an issue there.

**Comment by jan-ivar** [comment]
All webrtc-pc says is *"let* msids *be a list of the MSIDs that the media description* ***indicates*** *transceiver.[[Receiver]].[[ReceiverTrack]] is to be associated with. Otherwise, let* msids *be an empty list"*

And [mmusic](https://tools.ietf.org/html/draft-ietf-mmusic-msid-16#section-3) says *"The special value "-"* ***indicates*** *"no MediaStream"."*

So that already takes care of the `"-"` case correctly, I claim.

> I suppose we need some JSEP language to handle the lack of any a=msid

I agree. We need to solve what the *media description* (JSEP) says about this. Right now [it says](https://tools.ietf.org/html/draft-ietf-rtcweb-jsep-24#section-5.8.2):

***"If present,*** *"a=msid" attributes MUST be parsed as specified in [I-D.ietf-mmusic-msid], Section 3.2, and their values stored."*

I think it needs to say what happens when it is ***not*** present. Something like:

*"If no a=msid is present, then in place of "msid-id", create a single "id" unique to this end-point, if one hasn't already been created for this connection."*

**Comment by henbos** [comment]
> I think it needs to say what happens when it is _**not**_ present. Something like:
> 
> _"If no a=msid is present, then in place of "msid-id", create a single "id" unique to this end-point, if one hasn't already been created for this connection."_

"if one hasn't already been created for this connection"; so future tracks will share the same stream? There is always at most a single "default stream"?
