### ISSUE TITLE
52) [rfced] Throughout: <artwork> has been converted to

### ISSUE THREAD

**Issue by juberti** [rtcweb-wg/jsep#922]
52) [rfced] Throughout: <artwork> has been converted to
<sourcecode> as applicable and we set the "type" attribute.  Please
review and let us know corrections are needed.

**Comment by fluffy** [comment]
I reviewed these and believe they are correct (but sort of useless). It did make me think that we should provide the SVG versions of the ladder diagrams.

**Comment by fluffy** [comment]
This does look quite right. Section 2.5.7 of RFC 7991 makes me think the callflow's should be done with type artwork with type "call-flow" not sourcecode.  And the type for the ascii art should be "ascii-art" instead of ""

**Comment by fluffy** [comment]
Should I make a PR or RFC-ED ?

**Comment by juberti** [comment]
@ajeanmahoney for input

**Comment by ajeanmahoney** [comment]
I can see how the callflows in Sections 7.1, 7.2, and 7.3 were labeled pseudocode, since they look more like inputs for a callflow diagram generator (complete with comments), but I'm ok with them being labeled as artwork with type="ascii-art" (the type attribute has evolved to provide info to the output renderers. There's some discussion about it in Section 2.6.7 of this update to RFC 7991:  https://xml2rfc.tools.ietf.org/xml2rfc-doc.html)

**Comment by juberti** [comment]
@fluffy, can you advise here?

**Comment by fluffy** [comment]
I really don't care - I am happy with whatever @ajeanmahoney wants to use

**Comment by ajeanmahoney** [comment]
I will convert the call flows labeled with `<sourcecode type="pseudocode">` to `<artwork type="ascii-art">`. `type="call-flow"` is being deprecated.  See Section 2.6.7:
https://xml2rfc.tools.ietf.org/xml2rfc-doc.html#name-artwork-2
